### ISSUE TITLE
Calling oph_manage_session action=new raises exception

### ISSUE THREAD

**Issue by waltersf** [OphidiaBigData/PyOphidia#1]
Using latest version of PyOphidia and python 2.7.6 in Ubuntu 14.04. 

Calling `ophclient.submit("oph_manage_session action=new")` raises an exception, but a new session is created:

`(('/home/speed/walter/Envs/ophidia/lib/python2.7/site-packages/PyOphidia/client.pyc', 177), 'Something went wrong in submitting the request:', RuntimeError('Invalid jobid string',))`

I did not find any other way to create a new session besides using `ophclient.submit()`.

Field `ophclient.session` did not change its value to the new session id as well.

TIA

**Comment by eldoo** [comment]
Thanks for reporting this. The issue has been fixed.
