### ISSUE TITLE
sslv3 alert handshake failure when using Python 3.10

### ISSUE THREAD

**Issue by anfab** [OphidiaBigData/PyOphidia#41]
**`cube.Cube.setclient(read_env=True)`**

> ('/opt/conda/lib/python3.10/site-packages/PyOphidia/ophsubmit.py', 206) Something went wrong in submitting the request: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
> ('/opt/conda/lib/python3.10/site-packages/PyOphidia/client.py', 620) Something went wrong in resuming last session: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
> Current cdd is /
> Current cwd is /

See [https://bugs.python.org/issue43998](https://bugs.python.org/issue43998)

**Comment by minomicetto** [comment]
I just tested PyOphidia with CentOS9, where Ophidia Server certificates were installed using a new procedure according to the recent openssl libraries. The tests were successful with both Python 3.10.9 and 3.11.1.
I am going to summarize the procedure for creating certificates with the new procedure and explain how to resolve the issue.

**Comment by minomicetto** [comment]
Update openssl library used by Ophidia Server to version [3.0.7](https://www.openssl.org/source/openssl-3.0.7.tar.gz).
